apiVersion: v1
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: postgres-database-sc
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
  zone: us-central1-c
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
spec:
  storageClassName: postgres-database-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
