apiVersion: v1
kind: Service
metadata:
  name: planning-postgres-service
  labels:
    app: planning-postgres-service
    service: planning-postgres-service
spec:
  ports:
   - name: http
     protocol : TCP
     port: 5432
     targetPort: 5432
  selector:
    app: postgres
