name: planning-tool-postgres

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install the gcloud cli
        uses: google-github-actions/setup-gcloud@v0
        with:
         project_id: ncinga-reseller-incubator
         service_account_key: ${{ secrets.GOOGLE_CREDENTIALS }}
         export_default_credentials: true  
      - name: build and push the docker image
        env:
          GOOGLE_PROJECT: ncinga-reseller-incubator
        run: |
          gcloud auth configure-docker asia-south1-docker.pkg.dev
          docker build -t asia-south1-docker.pkg.dev/ncinga-reseller-incubator/docker-image/planning-tool-postgres:latest .
          docker push asia-south1-docker.pkg.dev/ncinga-reseller-incubator/docker-image/planning-tool-postgres:latest 
